baseurl = "/"
title = "Clarity"
author = "Chip Zoller"
copyright = "Copyright © 2008–2018, Steve Francia and the Hugo Authors; all rights reserved."
# canonifyurls = true
paginate = 10
theme = "hugo-clarity"

[markup]
  [markup.highlight]
    codeFences = true
    guessSyntax = true
    hl_Lines = "--"
    lineNoStart = 1
    lineNos = true
    lineNumbersInTable = false
    noClasses = false
    # style = "monokai"
    tabWidth = 2

[params]
author = "Chip Zoller"
introDescription = "Technologist, perpetual student, teacher, continual incremental improvement."
contentSharing = "I'm happy for you to share content on this site, but please provide attribution."
fallBackOgImage = "/images/thumbnail.png" # will be used on share >> twitter, facebook, linkedin 

blogDir = "post" # directory where your articles are

centerLogo = true # center logo on navbar
